name: Generate Snake Animation

on:
  # Run automatically once a day at midnight
  schedule:
    - cron: "0 0 * * *"

  # Allows manual trigger
  workflow_dispatch:

  # Run on push to main or master branch
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: "Piyush014"
          outputs: dist/github-contribution-grid-snake.svg

      # Upload the snake animation to the repository
      - name: Upload Snake to Repository
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
