name: Generate Snake Animation

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2  # Uses Platane's action to generate the contribution graph
        with:
          github_user_name: ${{ github.actor }}  # Uses the GitHub username of the actor (user who triggered the workflow)
          outputs: dist/github-contribution-grid-snake.svg  # Specifies the output SVG file path

      - name: Upload Snake to Repository
        uses: crazy-max/ghaction-github-pages@v2  # Uses the GitHub Pages action to deploy the file
        with:
          target_branch: output  # The branch where the output will be pushed
          build_dir: dist  # Directory where the generated files are located
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensures the action has permission to push to the repo
